/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DpaTokenGenerator {
        "handleSubmit": (event: any) => Promise<void>;
    }
    interface IntegratedCheckout {
    }
}
declare global {
    interface HTMLDpaTokenGeneratorElement extends Components.DpaTokenGenerator, HTMLStencilElement {
    }
    var HTMLDpaTokenGeneratorElement: {
        prototype: HTMLDpaTokenGeneratorElement;
        new (): HTMLDpaTokenGeneratorElement;
    };
    interface HTMLIntegratedCheckoutElement extends Components.IntegratedCheckout, HTMLStencilElement {
    }
    var HTMLIntegratedCheckoutElement: {
        prototype: HTMLIntegratedCheckoutElement;
        new (): HTMLIntegratedCheckoutElement;
    };
    interface HTMLElementTagNameMap {
        "dpa-token-generator": HTMLDpaTokenGeneratorElement;
        "integrated-checkout": HTMLIntegratedCheckoutElement;
    }
}
declare namespace LocalJSX {
    interface DpaTokenGenerator {
    }
    interface IntegratedCheckout {
    }
    interface IntrinsicElements {
        "dpa-token-generator": DpaTokenGenerator;
        "integrated-checkout": IntegratedCheckout;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dpa-token-generator": LocalJSX.DpaTokenGenerator & JSXBase.HTMLAttributes<HTMLDpaTokenGeneratorElement>;
            "integrated-checkout": LocalJSX.IntegratedCheckout & JSXBase.HTMLAttributes<HTMLIntegratedCheckoutElement>;
        }
    }
}
